CREATE DATABASE FootballConsoleDB;
GO

USE FootballConsoleDB;
GO

CREATE TABLE Country
(
    CountryID INT IDENTITY(1,1) PRIMARY KEY,
    CountryName VARCHAR(50) NOT NULL UNIQUE,
    Continent VARCHAR(20) NOT NULL
)
GO

CREATE TABLE Coach
(
    CoachID INT IDENTITY(1,1) PRIMARY KEY,
    CoachName VARCHAR(100) NOT NULL
)
GO

CREATE TABLE Team
(
    TeamID INT IDENTITY(1,1) PRIMARY KEY,
    TeamName VARCHAR(100) NOT NULL UNIQUE,
    CountryID INT NOT NULL,
    TeamType VARCHAR(20) NOT NULL,
    CoachID INT NOT NULL,

    FOREIGN KEY (CountryID) REFERENCES Country(CountryID),
    FOREIGN KEY (CoachID) REFERENCES Coach(CoachID)
)
GO

CREATE TABLE Player
(
    PlayerID INT IDENTITY(1,1) PRIMARY KEY,
    PlayerName VARCHAR(100) NOT NULL,
    ShirtNumber TINYINT NOT NULL,
    Position VARCHAR(10) NOT NULL,
    TeamID INT NOT NULL,

    FOREIGN KEY (TeamID) REFERENCES Team(TeamID),
    UNIQUE (TeamID, ShirtNumber),
    CHECK (ShirtNumber > 0 AND ShirtNumber < 100)
)
GO

CREATE TABLE Match
(
    MatchID INT IDENTITY(1,1) PRIMARY KEY,
    HomeTeamID INT NOT NULL,
    AwayTeamID INT NOT NULL,
    MatchDate DATETIME NOT NULL DEFAULT GETDATE(),

    FOREIGN KEY (HomeTeamID) REFERENCES Team(TeamID),
    FOREIGN KEY (AwayTeamID) REFERENCES Team(TeamID),
    CHECK (HomeTeamID <> AwayTeamID)
)
GO

CREATE TABLE Goal
(
    GoalID INT IDENTITY(1,1) PRIMARY KEY,
    MatchID INT NOT NULL,
    PlayerID INT NOT NULL,
    TeamGoal VARCHAR(10) NOT NULL,

    FOREIGN KEY (MatchID) REFERENCES Match(MatchID),
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
)
GO
